blank_issues_enabled: false
contact_links:
  - name: Task assignment
    about: Create a new task or feature.
    url: https://github.com/MyCityCO2/co2-switzerland/issues/new?template=TASK_ASSIGNMENT
  - name: Bug Report
    about: Create a report of the issue you've encountered.
    url: https://github.com/MyCityCO2/co2-switzerland/issues/new?template=BUG_REPORT
